# Generated by Django 3.0.5 on 2020-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20201008_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(choices=[(True, 'yes')], default=True),
        ),
    ]
