# Generated by Django 3.0.5 on 2020-10-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201008_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_artist',
            field=models.BooleanField(choices=[(True, 'Yes')], default=True),
        ),
    ]
