# Generated by Django 3.0.5 on 2020-10-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('client', '0004_auto_20201008_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mycart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
