# Generated by Django 3.0.5 on 2020-10-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('client', '0005_client_mycart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mycart',
        ),
        migrations.AddField(
            model_name='client',
            name='mycart',
            field=models.ManyToManyField(blank=True, null=True, to='cart.cart'),
        ),
    ]
