# Generated by Django 3.0.5 on 2020-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('client', '0006_auto_20201008_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mycart',
            field=models.ManyToManyField(blank=True, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
