# Generated by Django 3.0.5 on 2020-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('photo1', models.ImageField(default='profile.png', upload_to='photos/')),
                ('photo2', models.ImageField(default='profile.png', upload_to='photos/')),
                ('photo3', models.ImageField(default='profile.png', upload_to='photos/')),
                ('photo4', models.ImageField(default='profile.png', upload_to='photos/')),
                ('photo5', models.ImageField(default='profile.png', upload_to='photos/')),
            ],
        ),
    ]
