# Generated by Django 3.0.5 on 2020-10-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_arts'),
        ('client', '0010_remove_artist_arts'),
        ('artGallery', '0002_art_art_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.artist'),
        ),
        migrations.AddField(
            model_name='art',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
