# Generated by Django 3.0.5 on 2020-10-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artGallery', '0003_auto_20201013_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='art',
            name='cart',
        ),
    ]
