# Generated by Django 3.0 on 2020-10-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artGallery', '0004_auto_20201013_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='rating',
            new_name='quality',
        ),
    ]
