# Generated by Django 3.0 on 2020-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGallery', '0005_auto_20201017_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='photo1',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
