# Generated by Django 3.0 on 2020-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGallery', '0006_auto_20201205_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='art',
            name='photo2',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='photo3',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='photo4',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='photo5',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
