# Generated by Django 3.0 on 2020-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGallery', '0007_auto_20201205_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
