# Generated by Django 3.0 on 2020-11-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_auto_20201121_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='bid_amount',
        ),
    ]
