# Generated by Django 3.0 on 2020-11-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_auto_20201121_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
