# Generated by Django 3.0 on 2020-11-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20201014_1700'),
        ('exhibition', '0004_art_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.artist'),
        ),
        migrations.AlterField(
            model_name='art',
            name='exhibtion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.exhibtion'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.art'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
