# Generated by Django 3.0 on 2020-11-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_auto_20201121_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibtion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
