# Generated by Django 3.0.5 on 2020-10-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_cart_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='arts',
        ),
    ]
