# Generated by Django 3.0.5 on 2020-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGallery', '0004_auto_20201013_2304'),
        ('cart', '0003_remove_cart_arts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='art_list',
            field=models.ManyToManyField(blank=True, null=True, to='artGallery.art'),
        ),
    ]
